services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    command: ["sh", "-c", "python seed.py && flask run --host=0.0.0.0 --port=5000"]

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend  # Ensure frontend waits for backend to be up
