swagger: "2.0"
info:
  title: "Football Fan Zone API"
  description: "API for retrieving football-related data"
  version: "1.0.0"
paths:
  /teams:
    get:
      summary: "Retrieve all teams"
      responses:
        200:
          description: "List of teams"
  /players:
    get:
      summary: "Retrieve all players"
      responses:
        200:
          description: "List of players"
